### ISSUE TITLE
URL fragments dropped after redirect

### ISSUE THREAD

**Issue by omervk** [MachinePublishers/jBrowserDriver#92]
On some pages, the web page is not completely rendered when `getPageSource` is called. Calling `pageWait` or even `Thread.sleep` to wait for the script to run does not help.

Example: https://www.duolingo.com/privacy

**Comment by hollingsworthd** [comment]
Thanks for reporting this. Someone else had also and it's now fixed in master or 0.11.1-SNAPSHOT. Will be in next release.

**Comment by omervk** [comment]
That's great. Would you kindly point to the original issue?

**Comment by omervk** [comment]
@hollingsworthd Hi, I've just started using version 0.12.0 and this issue still exists...

**Comment by hollingsworthd** [comment]
@omervk does calling pageWait() help? Or try increasing ajaxWait to something higher than 150 ms `Settings.bulder().ajaxWait(..)`

**Comment by omervk** [comment]
@hollingsworthd I've had `pageWait` from the start and it didn't help. Added `ajaxWait` with higher and higher values, up to 10 seconds, and none work. You're can use the URL in the OP to debug the issue.

**Comment by hollingsworthd** [comment]
@omervk This is the source I get: http://pastebin.com/uw19pStZ

Is that not similar to what you're getting?

Also can you enable logging and post the output? `Settings.builder().logJavascript(true).logTrace(true).logWire(true)...`

**Comment by omervk** [comment]
That is definitely not what I'm seeing, but is indeed what I expected to see.

I took another look and found my mistake: It's actually http://duolingo.com/#/privacy and not http://duolingo.com/privacy. Running the latter works great, but the former fails.

**Comment by hollingsworthd** [comment]
I was able to reproduce this. Glad you found/reported this. Fix will be in next release. Thanks!

Background: fragments were not passed on redirects -- related info, http://stackoverflow.com/questions/2286402/url-fragment-and-302-redirects

**Comment by eos1d3** [comment]
This problem is still not fixed. For example (with JS enabled):

`https://auth.cbox.naver.com/oauth/login/twitter?redirectUrl=http%3A%2F%2Fentertain.naver.com%2Fcomment%2Flist%3Foid%3D057%26aid%3D0001050459%26lightVersion%3Don`

It is redirected to

`https://auth.cbox.naver.com/`

But actual redirection is

`http://entertain.naver.com/comment/list?oid=057&aid=0001050459&lightVersion=on`

using dependency of version 0.17.1
